version: '3'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    
  backend:
    env_file: .env
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
     - "5001:5001"
    depends_on:
     - "dynamodb-local"
    links:
     - "dynamodb-local"

  frontend:
    env_file: .env
    container_name: frontend  
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:8080"